In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s5e2/sample_submission.csv
/kaggle/input/playground-series-s5e2/train.csv
/kaggle/input/playground-series-s5e2/test.csv
/kaggle/input/playground-series-s5e2/training_extra.csv

In [2]:
!pip install cmaes

Collecting cmaes
  Downloading cmaes-0.11.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from cmaes) (1.26.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy->cmaes) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy->cmaes) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy->cmaes) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy->cmaes) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy->cmaes) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy->cmaes) (2.4.1)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->cmaes) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->cmaes) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy->cmaes) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy->cmaes) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy->cmaes) (2024.2.0)
Downloading cmaes-0.11.1-py3-none-any.whl (35 kB)
Installing collected packages: cmaes
Successfully installed cmaes-0.11.1

In [3]:
!pip install --upgrade optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.10/dist-packages (4.2.0)
Collecting optuna
  Downloading optuna-4.2.1-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (1.14.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.10/dist-packages (from optuna) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.36)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (1.3.9)
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (2.4.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->optuna) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->optuna) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy->optuna) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy->optuna) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy->optuna) (2024.2.0)
Downloading optuna-4.2.1-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 6.9 MB/s eta 0:00:00
Installing collected packages: optuna
  Attempting uninstall: optuna
    Found existing installation: optuna 4.2.0
    Uninstalling optuna-4.2.0:
      Successfully uninstalled optuna-4.2.0
Successfully installed optuna-4.2.1

In [4]:
!pip install --upgrade scikit-learn==1.4 --no-cache-dir

Collecting scikit-learn==1.4
  Downloading scikit_learn-1.4.0-1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.0,>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.4) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.4) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.4) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.4) (3.5.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy<2.0,>=1.19.5->scikit-learn==1.4) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy<2.0,>=1.19.5->scikit-learn==1.4) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy<2.0,>=1.19.5->scikit-learn==1.4) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy<2.0,>=1.19.5->scikit-learn==1.4) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy<2.0,>=1.19.5->scikit-learn==1.4) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy<2.0,>=1.19.5->scikit-learn==1.4) (2.4.1)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy<2.0,>=1.19.5->scikit-learn==1.4) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy<2.0,>=1.19.5->scikit-learn==1.4) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy<2.0,>=1.19.5->scikit-learn==1.4) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy<2.0,>=1.19.5->scikit-learn==1.4) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy<2.0,>=1.19.5->scikit-learn==1.4) (2024.2.0)
Downloading scikit_learn-1.4.0-1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 221.3 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
Successfully installed scikit-learn-1.4.0

In [5]:
#all import
import pandas as pd
import numpy as np
from functools import partial
from copy import deepcopy
import gc

# Import libraries for gradient boosting
import optuna
from optuna.samplers import CmaEsSampler
from sklearn.base import BaseEstimator, TransformerMixin
import xgboost as xgb
import lightgbm as lgb
# from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor, GradientBoostingRegressor
# from sklearn.svm import NuSVC, SVC
# from sklearn.neighbors import KNeighborsRegressor
# from sklearn.linear_model import LogisticRegression
# from sklearn.neural_network import MLPRegressor
# from sklearn.gaussian_process import GaussianProcessRegressor
# from sklearn.gaussian_process.kernels import RBF
from catboost import CatBoost, CatBoostRegressor, CatBoostRegressor
from catboost import Pool
from category_encoders import OneHotEncoder, OrdinalEncoder
from sklearn.metrics import root_mean_squared_error, log_loss
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, KFold

In [6]:
#read data 
df_train=pd.read_csv('/kaggle/input/playground-series-s5e2/train.csv')
df_train_xtra=pd.read_csv('/kaggle/input/playground-series-s5e2/training_extra.csv')
df_test=pd.read_csv('/kaggle/input/playground-series-s5e2/test.csv')
df_sub=pd.read_csv('/kaggle/input/playground-series-s5e2/sample_submission.csv')

In [7]:
missing_weight_ids=df_test[df_test['Weight Capacity (kg)'].isna()].id.values

In [8]:
df_train.id.values.max()

299999

In [9]:
#See all columns
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    300000 non-null  int64
 1   Brand                 290295 non-null  object
 2   Material              291653 non-null  object
 3   Size                  293405 non-null  object
 4   Compartments          300000 non-null  float64
 5   Laptop Compartment    292556 non-null  object
 6   Waterproof            292950 non-null  object
 7   Style                 292030 non-null  object
 8   Color                 290050 non-null  object
 9   Weight Capacity (kg)  299862 non-null  float64
 10  Price                 300000 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 25.2+ MB

In [10]:
df_train_xtra.id.values.max()

4194317

In [11]:
df_train_xtra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3694318 entries, 0 to 3694317
Data columns (total 11 columns):
 #   Column                Dtype
---  ------                -----
 0   id                    int64
 1   Brand                 object
 2   Material              object
 3   Size                  object
 4   Compartments          float64
 5   Laptop Compartment    object
 6   Waterproof            object
 7   Style                 object
 8   Color                 object
 9   Weight Capacity (kg)  float64
 10  Price                 float64
dtypes: float64(3), int64(1), object(7)
memory usage: 310.0+ MB

In [12]:
df_train=pd.concat([df_train,df_train_xtra])

In [13]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3994318 entries, 0 to 3694317
Data columns (total 11 columns):
 #   Column                Dtype
---  ------                -----
 0   id                    int64
 1   Brand                 object
 2   Material              object
 3   Size                  object
 4   Compartments          float64
 5   Laptop Compartment    object
 6   Waterproof            object
 7   Style                 object
 8   Color                 object
 9   Weight Capacity (kg)  float64
 10  Price                 float64
dtypes: float64(3), int64(1), object(7)
memory usage: 365.7+ MB

In [14]:
df_train[df_train['id']>299999]

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,500000,Under Armour,Canvas,Small,10.0,Yes,Yes,Tote,Blue,23.882052,114.11068
1,500001,Puma,Polyester,Small,4.0,No,Yes,Backpack,Green,11.869095,129.74972
2,500002,Jansport,Polyester,Small,8.0,Yes,Yes,Tote,Red,8.092302,21.37370
3,500003,Nike,Nylon,Large,7.0,No,No,Messenger,Pink,7.719581,48.09209
4,500004,Nike,Leather,Large,9.0,No,Yes,Tote,Green,22.741826,77.32461
...,...,...,...,...,...,...,...,...,...,...,...
3694313,4194313,Nike,Canvas,NaN,3.0,Yes,Yes,Messenger,Blue,28.098120,104.74460
3694314,4194314,Puma,Leather,Small,10.0,Yes,Yes,Tote,Blue,17.379531,122.39043
3694315,4194315,Jansport,Canvas,Large,10.0,No,No,Backpack,Red,17.037708,148.18470
3694316,4194316,Puma,Canvas,NaN,2.0,No,No,Backpack,Gray,28.783339,22.32269
3694317,4194317,Under Armour,Polyester,Medium,2.0,Yes,No,Backpack,Blue,23.076169,107.61199

In [15]:
df_train.isna().any()

id                      False
Brand                    True
Material                 True
Size                     True
Compartments            False
Laptop Compartment       True
Waterproof               True
Style                    True
Color                    True
Weight Capacity (kg)     True
Price                   False
dtype: bool

In [16]:
df_train=df_train.rename(columns={'Laptop Compartment':'Laptop_Compartment','Weight Capacity (kg)':'Weight_Capacity_(kg)'})
df_test=df_test.rename(columns={'Laptop Compartment':'Laptop_Compartment','Weight Capacity (kg)':'Weight_Capacity_(kg)'})

In [17]:
for c in df_train.columns:
    if c not in ['id','Compartments','Price']:
        if df_train[c].dtype==np.number:
            print(f'col {c}\t{df_train[c].min()},{df_train[c].max()},{df_train[c].mean()}')
        else:
            print(f'col {c}\t{df_train[c].unique()}')

<ipython-input-17-8652e0be35bb>:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df_train[c].dtype==np.number:

col Brand	['Jansport' 'Under Armour' 'Nike' 'Adidas' 'Puma' nan]
col Material	['Leather' 'Canvas' 'Nylon' nan 'Polyester']
col Size	['Medium' 'Small' 'Large' nan]
col Laptop_Compartment	['Yes' 'No' nan]
col Waterproof	['No' 'Yes' nan]
col Style	['Tote' 'Messenger' nan 'Backpack']
col Color	['Black' 'Green' 'Red' 'Blue' 'Gray' 'Pink' nan]
col Weight_Capacity_(kg)	5.0,30.0,18.0104168149865

In [18]:
for c in df_test.columns:
    if c not in ['id','Compartments','Price']:
        if df_test[c].dtype==np.number:
            print(f'col {c}\t{df_test[c].min()},{df_test[c].max()},{df_test[c].mean()}')
        else:
            print(f'col {c}\t{df_test[c].unique()}')

col Brand	['Puma' 'Nike' 'Adidas' nan 'Under Armour' 'Jansport']
col Material	['Leather' 'Canvas' 'Nylon' 'Polyester' nan]
col Size	['Small' 'Medium' 'Large' nan]
col Laptop_Compartment	['No' 'Yes' nan]
col Waterproof	['No' 'Yes' nan]
col Style	['Tote' 'Backpack' 'Messenger' nan]
col Color	['Green' 'Blue' 'Black' 'Red' 'Pink' 'Gray' nan]
col Weight_Capacity_(kg)	5.0,30.0,17.993033231213683

<ipython-input-18-fc51ea396d26>:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df_test[c].dtype==np.number:

In [19]:
#bag that has no weight values counts
df_train['Weight_Capacity_(kg)'].isna().value_counts()

Weight_Capacity_(kg)
False    3992510
True        1808
Name: count, dtype: int64

In [20]:
#One Hot encoder 
object_columns= df_train.select_dtypes('object').columns.to_list()
encoder = OneHotEncoder(cols=object_columns)
train_encoder = encoder.fit_transform(df_train[object_columns]).astype(int).add_suffix('_ohe')
test_encoder = encoder.transform(df_test[object_columns]).astype(int).add_suffix('_ohe')

In [21]:
#Drop original cols 
df_train=df_train.drop(object_columns,axis=1)
df_train=pd.concat([df_train,train_encoder],axis=1)

df_test=df_test.drop(object_columns,axis=1)
df_test=pd.concat([df_test,test_encoder],axis=1)

In [22]:
df_train=df_train.dropna()
#df_test=df_test.dropna()

In [23]:
df_train=df_train.drop('id',axis=1)
#df_test=df_test.drop('id',axis=1)

In [24]:
sc = StandardScaler()
df_train[['Weight_Capacity_(kg)']] = sc.fit_transform(df_train[['Weight_Capacity_(kg)']])
df_test[['Weight_Capacity_(kg)']] = sc.transform(df_test[['Weight_Capacity_(kg)']])

In [25]:
#Create input and label for predict missing weights
X_train_w=df_train.copy()
X_train_w=X_train_w.dropna()
y_train_w=X_train_w['Weight_Capacity_(kg)']
X_train_w=X_train_w.drop(['Price','Weight_Capacity_(kg)'],axis=1)

X_test_w=df_test[df_test['Weight_Capacity_(kg)'].isna()].drop(['id','Weight_Capacity_(kg)'],axis=1)  #73 row

In [26]:
X_train=df_train
y_train=df_train['Price']
X_test=df_test
X_test=X_test.drop('id',axis=1)

In [27]:
X_train=X_train.drop('Price',axis=1)

In [28]:
X_train.Compartments.value_counts()

Compartments
1.0     423158
4.0     417042
2.0     407873
3.0     406578
7.0     400723
5.0     399305
9.0     398054
10.0    396135
8.0     383065
6.0     360577
Name: count, dtype: int64

In [29]:
X_test.Compartments.value_counts()

Compartments
1.0     21203
4.0     20788
3.0     20366
7.0     20103
2.0     20079
5.0     20049
10.0    19850
9.0     19752
8.0     19433
6.0     18377
Name: count, dtype: int64

In [30]:
X_test.shape

(200000, 34)

# Optuna

In [31]:
class Regressor:
    def __init__(self, early_stopping_rounds,n_estimators=100, device="cpu", random_state=0):
        self.n_estimators = n_estimators
        self.device = device
        self.random_state = random_state
        self.early_stopping_rounds=early_stopping_rounds
        self.models = self._define_model()
        self.len_models = len(self.models)
        
    def _define_model(self):
        
        xgb_params = {
            'n_estimators': self.n_estimators,
            'learning_rate': 0.05,
            'max_depth': 7,
            'subsample': 1.0,
            'colsample_bytree': 1.0,
            'n_jobs': -1,
            'eval_metric': 'rmse',
            'objective': 'reg:squarederror',
            'verbosity': 0,
            'random_state': self.random_state,
            'early_stopping_rounds': self.early_stopping_rounds
        }
        if self.device == 'gpu':
            xgb_params['tree_method'] = 'gpu_hist'
            xgb_params['predictor'] = 'gpu_predictor'
        
        lgb_params = {
            'n_estimators': self.n_estimators,
            'max_depth': 7,
            'learning_rate': 0.05,
            'subsample': 0.20,
            'colsample_bytree': 0.56,
            'reg_alpha': 0.25,
            'reg_lambda': 5e-08,
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'device': self.device,
            'random_state': self.random_state,
            'early_stopping_rounds':self.early_stopping_rounds
        }
        
        cb_params = {
            'iterations': self.n_estimators,
            'depth': 7,
            'learning_rate': 0.1,
            'l2_leaf_reg': 0.7,
            'random_strength': 0.2,
            'max_bin': 200,
            'od_wait': 65,
            'one_hot_max_size': 70,
            'grow_policy': 'Depthwise',
            'bootstrap_type': 'Bayesian',
            'od_type': 'Iter',
            'eval_metric': 'RMSE',
            'loss_function': 'RMSE',
            'task_type': self.device.upper(),
            'random_state': self.random_state
        }
        
        models = {
            'xgb': xgb.XGBRegressor(**xgb_params),
            'lgb': lgb.LGBMRegressor(**lgb_params),
            'cat': CatBoostRegressor(**cb_params),
        }
        
        return models

In [32]:
class OptunaWeights:
    def __init__(self, random_state):
        self.study = None
        self.weights = None
        self.random_state = random_state

    def _objective(self, trial, y_true, y_preds):
        # Define the weights for the predictions from each model
        weights = [trial.suggest_float(f"weight{n}", 0, 1) for n in range(len(y_preds))]

        # Calculate the weighted prediction
        weighted_pred = np.average(np.array(y_preds).T, axis=1, weights=weights)

        # Calculate the AUC score for the weighted prediction
        score = root_mean_squared_error(y_true, weighted_pred)
        return score

    def fit(self, y_true, y_preds, n_trials=1000):
        optuna.logging.set_verbosity(optuna.logging.ERROR)
        sampler = optuna.samplers.CmaEsSampler(seed=self.random_state)
        self.study = optuna.create_study(sampler=sampler, study_name="OptunaWeights", direction='minimize')
        objective_partial = partial(self._objective, y_true=y_true, y_preds=y_preds)
        self.study.optimize(objective_partial, n_trials=n_trials)
        self.weights = [self.study.best_params[f"weight{n}"] for n in range(len(y_preds))]

    def predict(self, y_preds):
        assert self.weights is not None, 'OptunaWeights error, must be fitted before predict'
        weighted_pred = np.average(np.array(y_preds).T, axis=1, weights=self.weights)
        return weighted_pred

    def fit_predict(self, y_true, y_preds, n_trials=1000):
        self.fit(y_true, y_preds, n_trials=n_trials)
        return self.predict(y_preds)
    
    def weights(self):
        return self.weights
    
#Regression doesn't need ThresholdOptimizer
class ThresholdOptimizer:
    def __init__(self, y_true, y_preds, random_state):
        self.y_true = y_true
        self.y_preds = y_preds
        self.random_state = random_state
        self.sampler = optuna.samplers.CmaEsSampler(seed=self.random_state)
        self.study = optuna.create_study(sampler=self.sampler, study_name="OptunaWeights", direction='maximize')
        self.objective_partial = partial(self._objective, y_true=y_true, y_preds=y_preds)
        
    def _objective(self, trial, y_true, y_preds):
        threshold = trial.suggest_float("threshold", 0, 1)
        score = root_mean_squared_error(y_true, np.where(y_preds > threshold, 1, 0))
        return score
        
    def run_optimization(self, n_trials=1000):
        optuna.logging.set_verbosity(optuna.logging.ERROR)
        self.study.optimize(self.objective_partial, n_trials=n_trials)
        
    def get_best_threshold(self):
        return self.study.best_params["threshold"]

# Training

In [33]:
#TRain to find missing weights
n_splits = 5
random_state = 42
n_estimators = 5000 # 9999
early_stopping_rounds = 50
verbose = False
device = 'gpu'

# Initialize an array for storing test predictions
test_predss = np.zeros(X_test.shape[0])

test_predss_sub = []
ensemble_score = []
weights = []
regressor=Regressor(early_stopping_rounds=early_stopping_rounds)
trained_models = dict(zip(regressor.models.keys(), [[] for _ in range(regressor.len_models)]))

stratify_column=X_train['Compartments']

kf = StratifiedKFold(n_splits=n_splits, random_state=random_state, shuffle=True)
for i, (train_index, val_index) in enumerate(kf.split(X_train_w, stratify_column)):
    X_train_, X_val = X_train_w.iloc[train_index], X_train_w.iloc[val_index]
    y_train_, y_val = y_train_w.iloc[train_index], y_train_w.iloc[val_index]
        
    # Get a set of Regressor models
    rs = Regressor(early_stopping_rounds,n_estimators, device, random_state)
    models = rs.models
    
    # Initialize lists to store oof and test predictions for each base model
    oof_preds = []
    test_preds = []
    
    # Loop over each base model and fit it to the training data, evaluate on validation data, and store predictions
    for name, model in models.items():
        if name == 'cat_label':
            train_pool = Pool(X_train_, y_train_)#, cat_features=categorical_columns)
            test_pool = Pool(X_val, y_val)# ,cat_features=categorical_columns)
            model.fit(train_pool, eval_set=[test_pool], early_stopping_rounds=early_stopping_rounds, verbose=verbose)
        elif name == 'lgb_label':
            model.fit(X_train_, y_train_, eval_set=[(X_val, y_val)])
        elif name in ['xgb', 'lgb', 'cat']:
            model.fit(X_train_, y_train_, eval_set=[(X_val, y_val)])
        else:
            model.fit(X_train_fillna.iloc[train_index], y_train_)
        
        
        # if name in ['xgb', 'lgb', 'cat', 'cat_label', 'lgb_label']:
        #     test_pred = model.predict_proba(X_test)[:, 1]
        #     y_val_pred = model.predict_proba(X_val)[:, 1]
        # else:
        #     test_pred = model.predict_proba(X_test_fillna)[:, 1]
        #     y_val_pred = model.predict_proba(X_train_fillna.iloc[val_index])[:, 1]
        
        test_pred=model.predict(X_test_w)
        y_val_pred=model.predict(X_val)
        score = root_mean_squared_error(y_val, y_val_pred)
        print(f'{name} model [FOLD-{i}] RMSE: {score:.5f}')
        
        oof_preds.append(y_val_pred)
        test_preds.append(test_pred)
        trained_models[f'{name}'].append(deepcopy(model))
    
    # Use Optuna to find the best ensemble weights
    optweights = OptunaWeights(random_state=random_state)
    y_val_pred = optweights.fit_predict(y_val.values, oof_preds)

    #****** Not use Threshold because we do regression *****
    # Use Optuna to find the best threshold
    # opt = ThresholdOptimizer(y_val, y_val_pred, random_state)
    # opt.run_optimization(n_trials=2000)
    # best_threshold = opt.get_best_threshold()
    
    #score = accuracy_score(y_val, np.where(y_val_pred > best_threshold, 1, 0)) 
    score = root_mean_squared_error(y_val, y_val_pred)
    print(f'Ensemble [FOLD-{i}] RMSE score {score:.5f}')
    ensemble_score.append(score)
    weights.append(optweights.weights)
    
    test_predss_sub.append(optweights.predict(test_preds))
    print(f'result added {len(test_predss_sub)} items')
    #test_predss_onehot.append(np.where(optweights.predict(test_preds) > best_threshold, 1, 0))
    #gc.collect()

[0]	validation_0-rmse:0.99946
[1]	validation_0-rmse:0.99943
[2]	validation_0-rmse:0.99941
[3]	validation_0-rmse:0.99939
[4]	validation_0-rmse:0.99938
[5]	validation_0-rmse:0.99936
[6]	validation_0-rmse:0.99935
[7]	validation_0-rmse:0.99933
[8]	validation_0-rmse:0.99932
[9]	validation_0-rmse:0.99931
[10]	validation_0-rmse:0.99930
[11]	validation_0-rmse:0.99929
[12]	validation_0-rmse:0.99929
[13]	validation_0-rmse:0.99928
[14]	validation_0-rmse:0.99927
[15]	validation_0-rmse:0.99927
[16]	validation_0-rmse:0.99926
[17]	validation_0-rmse:0.99926
[18]	validation_0-rmse:0.99925
[19]	validation_0-rmse:0.99925
[20]	validation_0-rmse:0.99925
[21]	validation_0-rmse:0.99924
[22]	validation_0-rmse:0.99924
[23]	validation_0-rmse:0.99923
[24]	validation_0-rmse:0.99923
[25]	validation_0-rmse:0.99923
[26]	validation_0-rmse:0.99922
[27]	validation_0-rmse:0.99922
[28]	validation_0-rmse:0.99922
[29]	validation_0-rmse:0.99922
[30]	validation_0-rmse:0.99921
[31]	validation_0-rmse:0.99921
[32]	validation_0-rmse:0.99921
[33]	validation_0-rmse:0.99921
[34]	validation_0-rmse:0.99921
[35]	validation_0-rmse:0.99920
[36]	validation_0-rmse:0.99920
[37]	validation_0-rmse:0.99920
[38]	validation_0-rmse:0.99920
[39]	validation_0-rmse:0.99920
[40]	validation_0-rmse:0.99920
[41]	validation_0-rmse:0.99920
[42]	validation_0-rmse:0.99920
[43]	validation_0-rmse:0.99920
[44]	validation_0-rmse:0.99920
[45]	validation_0-rmse:0.99920
[46]	validation_0-rmse:0.99920
[47]	validation_0-rmse:0.99920
[48]	validation_0-rmse:0.99920
[49]	validation_0-rmse:0.99920
[50]	validation_0-rmse:0.99920
[51]	validation_0-rmse:0.99920
[52]	validation_0-rmse:0.99920
[53]	validation_0-rmse:0.99920
[54]	validation_0-rmse:0.99920
[55]	validation_0-rmse:0.99920
[56]	validation_0-rmse:0.99920
[57]	validation_0-rmse:0.99920
[58]	validation_0-rmse:0.99920
[59]	validation_0-rmse:0.99920
[60]	validation_0-rmse:0.99920
[61]	validation_0-rmse:0.99920
[62]	validation_0-rmse:0.99920
[63]	validation_0-rmse:0.99920
[64]	validation_0-rmse:0.99920
[65]	validation_0-rmse:0.99920
[66]	validation_0-rmse:0.99920
[67]	validation_0-rmse:0.99921
[68]	validation_0-rmse:0.99921
[69]	validation_0-rmse:0.99921
[70]	validation_0-rmse:0.99921
[71]	validation_0-rmse:0.99921
[72]	validation_0-rmse:0.99921
[73]	validation_0-rmse:0.99921
[74]	validation_0-rmse:0.99921
[75]	validation_0-rmse:0.99921
[76]	validation_0-rmse:0.99921
[77]	validation_0-rmse:0.99921
[78]	validation_0-rmse:0.99921
[79]	validation_0-rmse:0.99921
[80]	validation_0-rmse:0.99921
[81]	validation_0-rmse:0.99921
[82]	validation_0-rmse:0.99921
[83]	validation_0-rmse:0.99921
[84]	validation_0-rmse:0.99921
[85]	validation_0-rmse:0.99921
[86]	validation_0-rmse:0.99922
[87]	validation_0-rmse:0.99922
[88]	validation_0-rmse:0.99922
[89]	validation_0-rmse:0.99922
[90]	validation_0-rmse:0.99922
[91]	validation_0-rmse:0.99922
[92]	validation_0-rmse:0.99922
[93]	validation_0-rmse:0.99922
[94]	validation_0-rmse:0.99922
[95]	validation_0-rmse:0.99922
[96]	validation_0-rmse:0.99922
[97]	validation_0-rmse:0.99922
[98]	validation_0-rmse:0.99922
[99]	validation_0-rmse:0.99922
[100]	validation_0-rmse:0.99923
[101]	validation_0-rmse:0.99923
[102]	validation_0-rmse:0.99923
xgb model [FOLD-0] RMSE: 0.99920
[LightGBM] [Warning] early_stopping_round is set=50, early_stopping_rounds=50 will be ignored. Current value: early_stopping_round=50
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 75
[LightGBM] [Info] Number of data points in the train set: 3194008, number of used features: 33
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 16 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 8 dense feature groups (12.18 MB) transferred to GPU in 0.063246 secs. 0 sparse feature groups
[LightGBM] [Warning] early_stopping_round is set=50, early_stopping_rounds=50 will be ignored. Current value: early_stopping_round=50
[LightGBM] [Info] Start training from score 0.000091
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[152]	valid_0's rmse: 0.999155
lgb model [FOLD-0] RMSE: 0.99916
0:	learn: 1.0000729	test: 0.9994390	best: 0.9994390 (0)	total: 257ms	remaining: 21m 24s
1:	learn: 1.0000223	test: 0.9993999	best: 0.9993999 (1)	total: 287ms	remaining: 11m 57s
2:	learn: 0.9999814	test: 0.9993680	best: 0.9993680 (2)	total: 316ms	remaining: 8m 46s
3:	learn: 0.9999426	test: 0.9993414	best: 0.9993414 (3)	total: 344ms	remaining: 7m 9s
4:	learn: 0.9999109	test: 0.9993161	best: 0.9993161 (4)	total: 372ms	remaining: 6m 11s
5:	learn: 0.9998844	test: 0.9993002	best: 0.9993002 (5)	total: 399ms	remaining: 5m 32s
6:	learn: 0.9998602	test: 0.9992869	best: 0.9992869 (6)	total: 428ms	remaining: 5m 5s
7:	learn: 0.9998371	test: 0.9992724	best: 0.9992724 (7)	total: 454ms	remaining: 4m 43s
8:	learn: 0.9998142	test: 0.9992593	best: 0.9992593 (8)	total: 482ms	remaining: 4m 27s
9:	learn: 0.9997951	test: 0.9992471	best: 0.9992471 (9)	total: 509ms	remaining: 4m 14s
10:	learn: 0.9997773	test: 0.9992384	best: 0.9992384 (10)	total: 534ms	remaining: 4m 2s
11:	learn: 0.9997630	test: 0.9992331	best: 0.9992331 (11)	total: 560ms	remaining: 3m 52s
12:	learn: 0.9997472	test: 0.9992288	best: 0.9992288 (12)	total: 585ms	remaining: 3m 44s
13:	learn: 0.9997317	test: 0.9992243	best: 0.9992243 (13)	total: 610ms	remaining: 3m 37s
14:	learn: 0.9997179	test: 0.9992209	best: 0.9992209 (14)	total: 633ms	remaining: 3m 30s
15:	learn: 0.9997025	test: 0.9992149	best: 0.9992149 (15)	total: 656ms	remaining: 3m 24s
16:	learn: 0.9996899	test: 0.9992120	best: 0.9992120 (16)	total: 677ms	remaining: 3m 18s
17:	learn: 0.9996778	test: 0.9992106	best: 0.9992106 (17)	total: 700ms	remaining: 3m 13s
18:	learn: 0.9996651	test: 0.9992078	best: 0.9992078 (18)	total: 720ms	remaining: 3m 8s
19:	learn: 0.9996537	test: 0.9992055	best: 0.9992055 (19)	total: 741ms	remaining: 3m 4s
20:	learn: 0.9996422	test: 0.9992012	best: 0.9992012 (20)	total: 761ms	remaining: 3m
21:	learn: 0.9996306	test: 0.9991992	best: 0.9991992 (21)	total: 780ms	remaining: 2m 56s
22:	learn: 0.9996204	test: 0.9991982	best: 0.9991982 (22)	total: 800ms	remaining: 2m 53s
23:	learn: 0.9996117	test: 0.9991978	best: 0.9991978 (23)	total: 821ms	remaining: 2m 50s
24:	learn: 0.9996023	test: 0.9991945	best: 0.9991945 (24)	total: 841ms	remaining: 2m 47s
25:	learn: 0.9995940	test: 0.9991939	best: 0.9991939 (25)	total: 861ms	remaining: 2m 44s
26:	learn: 0.9995851	test: 0.9991924	best: 0.9991924 (26)	total: 881ms	remaining: 2m 42s
27:	learn: 0.9995743	test: 0.9991913	best: 0.9991913 (27)	total: 902ms	remaining: 2m 40s
28:	learn: 0.9995646	test: 0.9991911	best: 0.9991911 (28)	total: 922ms	remaining: 2m 38s
29:	learn: 0.9995550	test: 0.9991903	best: 0.9991903 (29)	total: 943ms	remaining: 2m 36s
30:	learn: 0.9995471	test: 0.9991888	best: 0.9991888 (30)	total: 963ms	remaining: 2m 34s
31:	learn: 0.9995375	test: 0.9991859	best: 0.9991859 (31)	total: 982ms	remaining: 2m 32s
32:	learn: 0.9995282	test: 0.9991849	best: 0.9991849 (32)	total: 1s	remaining: 2m 30s
33:	learn: 0.9995205	test: 0.9991831	best: 0.9991831 (33)	total: 1.02s	remaining: 2m 29s
34:	learn: 0.9995126	test: 0.9991828	best: 0.9991828 (34)	total: 1.04s	remaining: 2m 28s
35:	learn: 0.9995047	test: 0.9991820	best: 0.9991820 (35)	total: 1.07s	remaining: 2m 27s
36:	learn: 0.9994971	test: 0.9991815	best: 0.9991815 (36)	total: 1.09s	remaining: 2m 25s
37:	learn: 0.9994882	test: 0.9991817	best: 0.9991815 (36)	total: 1.11s	remaining: 2m 24s
38:	learn: 0.9994794	test: 0.9991794	best: 0.9991794 (38)	total: 1.13s	remaining: 2m 23s
39:	learn: 0.9994712	test: 0.9991784	best: 0.9991784 (39)	total: 1.15s	remaining: 2m 22s
40:	learn: 0.9994638	test: 0.9991792	best: 0.9991784 (39)	total: 1.17s	remaining: 2m 21s
41:	learn: 0.9994542	test: 0.9991799	best: 0.9991784 (39)	total: 1.19s	remaining: 2m 20s
42:	learn: 0.9994457	test: 0.9991808	best: 0.9991784 (39)	total: 1.21s	remaining: 2m 19s
43:	learn: 0.9994373	test: 0.9991815	best: 0.9991784 (39)	total: 1.23s	remaining: 2m 18s
44:	learn: 0.9994301	test: 0.9991821	best: 0.9991784 (39)	total: 1.25s	remaining: 2m 17s
45:	learn: 0.9994224	test: 0.9991825	best: 0.9991784 (39)	total: 1.27s	remaining: 2m 16s
46:	learn: 0.9994142	test: 0.9991832	best: 0.9991784 (39)	total: 1.29s	remaining: 2m 15s
47:	learn: 0.9994085	test: 0.9991829	best: 0.9991784 (39)	total: 1.31s	remaining: 2m 14s
48:	learn: 0.9993995	test: 0.9991835	best: 0.9991784 (39)	total: 1.33s	remaining: 2m 14s
49:	learn: 0.9993916	test: 0.9991850	best: 0.9991784 (39)	total: 1.35s	remaining: 2m 13s
50:	learn: 0.9993851	test: 0.9991853	best: 0.9991784 (39)	total: 1.37s	remaining: 2m 12s
51:	learn: 0.9993778	test: 0.9991856	best: 0.9991784 (39)	total: 1.39s	remaining: 2m 12s
52:	learn: 0.9993701	test: 0.9991849	best: 0.9991784 (39)	total: 1.41s	remaining: 2m 11s
53:	learn: 0.9993625	test: 0.9991847	best: 0.9991784 (39)	total: 1.43s	remaining: 2m 11s
54:	learn: 0.9993562	test: 0.9991856	best: 0.9991784 (39)	total: 1.45s	remaining: 2m 10s
55:	learn: 0.9993493	test: 0.9991856	best: 0.9991784 (39)	total: 1.47s	remaining: 2m 10s
56:	learn: 0.9993410	test: 0.9991854	best: 0.9991784 (39)	total: 1.49s	remaining: 2m 9s
57:	learn: 0.9993340	test: 0.9991863	best: 0.9991784 (39)	total: 1.51s	remaining: 2m 9s
58:	learn: 0.9993249	test: 0.9991846	best: 0.9991784 (39)	total: 1.53s	remaining: 2m 8s
59:	learn: 0.9993184	test: 0.9991842	best: 0.9991784 (39)	total: 1.55s	remaining: 2m 7s
60:	learn: 0.9993118	test: 0.9991857	best: 0.9991784 (39)	total: 1.58s	remaining: 2m 7s
61:	learn: 0.9993053	test: 0.9991851	best: 0.9991784 (39)	total: 1.6s	remaining: 2m 7s
62:	learn: 0.9992996	test: 0.9991865	best: 0.9991784 (39)	total: 1.62s	remaining: 2m 6s
63:	learn: 0.9992932	test: 0.9991879	best: 0.9991784 (39)	total: 1.64s	remaining: 2m 6s
64:	learn: 0.9992860	test: 0.9991886	best: 0.9991784 (39)	total: 1.66s	remaining: 2m 5s
65:	learn: 0.9992798	test: 0.9991900	best: 0.9991784 (39)	total: 1.68s	remaining: 2m 5s
66:	learn: 0.9992743	test: 0.9991900	best: 0.9991784 (39)	total: 1.7s	remaining: 2m 5s
67:	learn: 0.9992673	test: 0.9991910	best: 0.9991784 (39)	total: 1.72s	remaining: 2m 4s
68:	learn: 0.9992614	test: 0.9991904	best: 0.9991784 (39)	total: 1.74s	remaining: 2m 4s
69:	learn: 0.9992560	test: 0.9991915	best: 0.9991784 (39)	total: 1.76s	remaining: 2m 4s
70:	learn: 0.9992492	test: 0.9991929	best: 0.9991784 (39)	total: 1.78s	remaining: 2m 3s
71:	learn: 0.9992430	test: 0.9991945	best: 0.9991784 (39)	total: 1.8s	remaining: 2m 3s
72:	learn: 0.9992373	test: 0.9991950	best: 0.9991784 (39)	total: 1.82s	remaining: 2m 3s
73:	learn: 0.9992308	test: 0.9991979	best: 0.9991784 (39)	total: 1.85s	remaining: 2m 2s
74:	learn: 0.9992241	test: 0.9991995	best: 0.9991784 (39)	total: 1.87s	remaining: 2m 2s
75:	learn: 0.9992183	test: 0.9992002	best: 0.9991784 (39)	total: 1.9s	remaining: 2m 3s
76:	learn: 0.9992117	test: 0.9991994	best: 0.9991784 (39)	total: 1.93s	remaining: 2m 3s
77:	learn: 0.9992049	test: 0.9992011	best: 0.9991784 (39)	total: 1.97s	remaining: 2m 4s
78:	learn: 0.9991986	test: 0.9992027	best: 0.9991784 (39)	total: 1.99s	remaining: 2m 4s
79:	learn: 0.9991929	test: 0.9992049	best: 0.9991784 (39)	total: 2.02s	remaining: 2m 4s
80:	learn: 0.9991869	test: 0.9992069	best: 0.9991784 (39)	total: 2.04s	remaining: 2m 4s
81:	learn: 0.9991822	test: 0.9992086	best: 0.9991784 (39)	total: 2.07s	remaining: 2m 3s
82:	learn: 0.9991758	test: 0.9992080	best: 0.9991784 (39)	total: 2.09s	remaining: 2m 3s
83:	learn: 0.9991702	test: 0.9992084	best: 0.9991784 (39)	total: 2.11s	remaining: 2m 3s
84:	learn: 0.9991629	test: 0.9992098	best: 0.9991784 (39)	total: 2.14s	remaining: 2m 3s
85:	learn: 0.9991571	test: 0.9992108	best: 0.9991784 (39)	total: 2.16s	remaining: 2m 3s
86:	learn: 0.9991514	test: 0.9992127	best: 0.9991784 (39)	total: 2.21s	remaining: 2m 4s
87:	learn: 0.9991456	test: 0.9992136	best: 0.9991784 (39)	total: 2.23s	remaining: 2m 4s
88:	learn: 0.9991393	test: 0.9992151	best: 0.9991784 (39)	total: 2.26s	remaining: 2m 4s
89:	learn: 0.9991341	test: 0.9992165	best: 0.9991784 (39)	total: 2.28s	remaining: 2m 4s
90:	learn: 0.9991269	test: 0.9992167	best: 0.9991784 (39)	total: 2.3s	remaining: 2m 4s
91:	learn: 0.9991217	test: 0.9992183	best: 0.9991784 (39)	total: 2.33s	remaining: 2m 4s
92:	learn: 0.9991156	test: 0.9992210	best: 0.9991784 (39)	total: 2.35s	remaining: 2m 4s
93:	learn: 0.9991094	test: 0.9992223	best: 0.9991784 (39)	total: 2.38s	remaining: 2m 4s
94:	learn: 0.9991040	test: 0.9992214	best: 0.9991784 (39)	total: 2.4s	remaining: 2m 3s
95:	learn: 0.9990982	test: 0.9992227	best: 0.9991784 (39)	total: 2.42s	remaining: 2m 3s
96:	learn: 0.9990927	test: 0.9992243	best: 0.9991784 (39)	total: 2.46s	remaining: 2m 4s
97:	learn: 0.9990866	test: 0.9992268	best: 0.9991784 (39)	total: 2.48s	remaining: 2m 4s
98:	learn: 0.9990811	test: 0.9992272	best: 0.9991784 (39)	total: 2.51s	remaining: 2m 4s
99:	learn: 0.9990759	test: 0.9992286	best: 0.9991784 (39)	total: 2.53s	remaining: 2m 4s
100:	learn: 0.9990701	test: 0.9992301	best: 0.9991784 (39)	total: 2.56s	remaining: 2m 3s
101:	learn: 0.9990642	test: 0.9992315	best: 0.9991784 (39)	total: 2.58s	remaining: 2m 3s
102:	learn: 0.9990587	test: 0.9992312	best: 0.9991784 (39)	total: 2.6s	remaining: 2m 3s
103:	learn: 0.9990529	test: 0.9992305	best: 0.9991784 (39)	total: 2.63s	remaining: 2m 3s
104:	learn: 0.9990475	test: 0.9992322	best: 0.9991784 (39)	total: 2.65s	remaining: 2m 3s
bestTest = 0.9991784373
bestIteration = 39
Shrink model to first 40 iterations.
cat model [FOLD-0] RMSE: 0.99918
Ensemble [FOLD-0] RMSE score 0.99916
result added 1 items
[0]	validation_0-rmse:0.99952
[1]	validation_0-rmse:0.99949
[2]	validation_0-rmse:0.99947
[3]	validation_0-rmse:0.99945
[4]	validation_0-rmse:0.99943
[5]	validation_0-rmse:0.99941
[6]	validation_0-rmse:0.99940
[7]	validation_0-rmse:0.99938
[8]	validation_0-rmse:0.99937
[9]	validation_0-rmse:0.99936
[10]	validation_0-rmse:0.99935
[11]	validation_0-rmse:0.99934
[12]	validation_0-rmse:0.99933
[13]	validation_0-rmse:0.99932
[14]	validation_0-rmse:0.99932
[15]	validation_0-rmse:0.99931
[16]	validation_0-rmse:0.99930
[17]	validation_0-rmse:0.99930
[18]	validation_0-rmse:0.99929
[19]	validation_0-rmse:0.99928
[20]	validation_0-rmse:0.99928
[21]	validation_0-rmse:0.99927
[22]	validation_0-rmse:0.99927
[23]	validation_0-rmse:0.99926
[24]	validation_0-rmse:0.99926
[25]	validation_0-rmse:0.99926
[26]	validation_0-rmse:0.99926
[27]	validation_0-rmse:0.99925
[28]	validation_0-rmse:0.99925
[29]	validation_0-rmse:0.99925
[30]	validation_0-rmse:0.99925
[31]	validation_0-rmse:0.99924
[32]	validation_0-rmse:0.99924
[33]	validation_0-rmse:0.99924
[34]	validation_0-rmse:0.99924
[35]	validation_0-rmse:0.99924
[36]	validation_0-rmse:0.99923
[37]	validation_0-rmse:0.99923
[38]	validation_0-rmse:0.99923
[39]	validation_0-rmse:0.99923
[40]	validation_0-rmse:0.99923
[41]	validation_0-rmse:0.99923
[42]	validation_0-rmse:0.99923
[43]	validation_0-rmse:0.99922
[44]	validation_0-rmse:0.99922
[45]	validation_0-rmse:0.99922
[46]	validation_0-rmse:0.99922
[47]	validation_0-rmse:0.99922
[48]	validation_0-rmse:0.99922
[49]	validation_0-rmse:0.99922
[50]	validation_0-rmse:0.99922
[51]	validation_0-rmse:0.99922
[52]	validation_0-rmse:0.99922
[53]	validation_0-rmse:0.99922
[54]	validation_0-rmse:0.99922
[55]	validation_0-rmse:0.99922
[56]	validation_0-rmse:0.99922
[57]	validation_0-rmse:0.99922
[58]	validation_0-rmse:0.99922
[59]	validation_0-rmse:0.99922
[60]	validation_0-rmse:0.99922
[61]	validation_0-rmse:0.99922
[62]	validation_0-rmse:0.99922
[63]	validation_0-rmse:0.99922
[64]	validation_0-rmse:0.99922
[65]	validation_0-rmse:0.99922
[66]	validation_0-rmse:0.99922
[67]	validation_0-rmse:0.99922
[68]	validation_0-rmse:0.99922
[69]	validation_0-rmse:0.99922
[70]	validation_0-rmse:0.99922
[71]	validation_0-rmse:0.99922
[72]	validation_0-rmse:0.99922
[73]	validation_0-rmse:0.99922
[74]	validation_0-rmse:0.99922
[75]	validation_0-rmse:0.99922
[76]	validation_0-rmse:0.99922
[77]	validation_0-rmse:0.99922
[78]	validation_0-rmse:0.99922
[79]	validation_0-rmse:0.99923
[80]	validation_0-rmse:0.99923
[81]	validation_0-rmse:0.99923
[82]	validation_0-rmse:0.99923
[83]	validation_0-rmse:0.99923
[84]	validation_0-rmse:0.99923
[85]	validation_0-rmse:0.99923
[86]	validation_0-rmse:0.99923
[87]	validation_0-rmse:0.99923
[88]	validation_0-rmse:0.99923
[89]	validation_0-rmse:0.99923
[90]	validation_0-rmse:0.99923
[91]	validation_0-rmse:0.99923
[92]	validation_0-rmse:0.99923
[93]	validation_0-rmse:0.99923
[94]	validation_0-rmse:0.99923
[95]	validation_0-rmse:0.99923
[96]	validation_0-rmse:0.99923
[97]	validation_0-rmse:0.99923
[98]	validation_0-rmse:0.99923
[99]	validation_0-rmse:0.99924
[100]	validation_0-rmse:0.99924
[101]	validation_0-rmse:0.99924
[102]	validation_0-rmse:0.99924
[103]	validation_0-rmse:0.99924
[104]	validation_0-rmse:0.99924
[105]	validation_0-rmse:0.99924
[106]	validation_0-rmse:0.99924
[107]	validation_0-rmse:0.99924
[108]	validation_0-rmse:0.99925
[109]	validation_0-rmse:0.99925
[110]	validation_0-rmse:0.99925
[111]	validation_0-rmse:0.99925
[112]	validation_0-rmse:0.99925
[113]	validation_0-rmse:0.99925
[114]	validation_0-rmse:0.99925
xgb model [FOLD-1] RMSE: 0.99922
[LightGBM] [Warning] early_stopping_round is set=50, early_stopping_rounds=50 will be ignored. Current value: early_stopping_round=50
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 75
[LightGBM] [Info] Number of data points in the train set: 3194008, number of used features: 33
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 16 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 8 dense feature groups (12.18 MB) transferred to GPU in 0.055926 secs. 0 sparse feature groups
[LightGBM] [Warning] early_stopping_round is set=50, early_stopping_rounds=50 will be ignored. Current value: early_stopping_round=50
[LightGBM] [Info] Start training from score -0.000218
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[128]	valid_0's rmse: 0.999179
lgb model [FOLD-1] RMSE: 0.99918
0:	learn: 1.0000561	test: 0.9994952	best: 0.9994952 (0)	total: 31.2ms	remaining: 2m 35s
1:	learn: 1.0000081	test: 0.9994550	best: 0.9994550 (1)	total: 60.6ms	remaining: 2m 31s
2:	learn: 0.9999674	test: 0.9994176	best: 0.9994176 (2)	total: 88.2ms	remaining: 2m 26s
3:	learn: 0.9999314	test: 0.9993888	best: 0.9993888 (3)	total: 117ms	remaining: 2m 26s
4:	learn: 0.9998991	test: 0.9993614	best: 0.9993614 (4)	total: 147ms	remaining: 2m 27s
5:	learn: 0.9998728	test: 0.9993412	best: 0.9993412 (5)	total: 177ms	remaining: 2m 27s
6:	learn: 0.9998466	test: 0.9993219	best: 0.9993219 (6)	total: 204ms	remaining: 2m 25s
7:	learn: 0.9998225	test: 0.9993066	best: 0.9993066 (7)	total: 232ms	remaining: 2m 24s
8:	learn: 0.9998044	test: 0.9992925	best: 0.9992925 (8)	total: 262ms	remaining: 2m 25s
9:	learn: 0.9997864	test: 0.9992832	best: 0.9992832 (9)	total: 291ms	remaining: 2m 25s
10:	learn: 0.9997667	test: 0.9992724	best: 0.9992724 (10)	total: 318ms	remaining: 2m 24s
11:	learn: 0.9997510	test: 0.9992646	best: 0.9992646 (11)	total: 341ms	remaining: 2m 21s
12:	learn: 0.9997372	test: 0.9992590	best: 0.9992590 (12)	total: 364ms	remaining: 2m 19s
13:	learn: 0.9997217	test: 0.9992543	best: 0.9992543 (13)	total: 388ms	remaining: 2m 18s
14:	learn: 0.9997087	test: 0.9992499	best: 0.9992499 (14)	total: 413ms	remaining: 2m 17s
15:	learn: 0.9996987	test: 0.9992464	best: 0.9992464 (15)	total: 438ms	remaining: 2m 16s
16:	learn: 0.9996855	test: 0.9992418	best: 0.9992418 (16)	total: 462ms	remaining: 2m 15s
17:	learn: 0.9996729	test: 0.9992370	best: 0.9992370 (17)	total: 487ms	remaining: 2m 14s
18:	learn: 0.9996613	test: 0.9992322	best: 0.9992322 (18)	total: 513ms	remaining: 2m 14s

In [34]:
#The missing weight capacity
np.median(test_predss_sub, axis=0).reshape(-1,1).flatten()

array([ 0.06741025, -0.12791681,  0.09734696,  0.35094072, -0.03259109,
        0.03264037,  0.42217257,  0.02400568,  0.35894367,  0.38577381,
        0.01697508,  0.05829769, -0.02178566,  0.05426878,  0.03740318,
        0.03698445,  0.03112688,  0.05304039,  0.03832425,  0.04114402,
        0.05271335, -0.01616696, -0.03062218,  0.13107824,  0.04035122,
       -0.0532125 ,  0.0078274 ,  0.13743226, -0.01072255,  0.17255062,
       -0.03546497, -0.06388955,  0.00176594,  0.00258538, -0.00256121,
        0.03510546,  0.00672631,  0.06719677,  0.07195068,  0.07994927,
        0.37856847, -0.10088725,  0.05550055,  0.02252712,  0.00951064,
       -0.03248443,  0.07067256,  0.02059611, -0.01079954,  0.04392741,
        0.06128727,  0.00557696,  0.06848532,  0.07289732,  0.07374648,
        0.01064964,  0.02058298,  0.01530033, -0.03214861,  0.05709394,
        0.04496775,  0.04245212,  0.3519916 , -0.11576178,  0.04220285,
        0.05533076,  0.01027735, -0.08976909,  0.0539236 ,  0.45617822,
       -0.04752467,  0.32200296, -0.16514738,  0.08653695, -0.00669442,
        0.40036429,  0.02202281])

In [35]:
X_test.isna().any()

Compartments                False
Weight_Capacity_(kg)         True
Brand_1_ohe                 False
Brand_2_ohe                 False
Brand_3_ohe                 False
Brand_4_ohe                 False
Brand_5_ohe                 False
Brand_6_ohe                 False
Material_1_ohe              False
Material_2_ohe              False
Material_3_ohe              False
Material_4_ohe              False
Material_5_ohe              False
Size_1_ohe                  False
Size_2_ohe                  False
Size_3_ohe                  False
Size_4_ohe                  False
Laptop_Compartment_1_ohe    False
Laptop_Compartment_2_ohe    False
Laptop_Compartment_3_ohe    False
Waterproof_1_ohe            False
Waterproof_2_ohe            False
Waterproof_3_ohe            False
Style_1_ohe                 False
Style_2_ohe                 False
Style_3_ohe                 False
Style_4_ohe                 False
Color_1_ohe                 False
Color_2_ohe                 False
Color_3_ohe                 False
Color_4_ohe                 False
Color_5_ohe                 False
Color_6_ohe                 False
Color_7_ohe                 False
dtype: bool

In [36]:
df_test.loc[df_test.id.isin(missing_weight_ids),['Weight_Capacity_(kg)']] = np.median(test_predss_sub, axis=0).reshape(-1,1).flatten()
df_test[df_test.id.isin(missing_weight_ids)]['Weight_Capacity_(kg)']

1350      0.067410
1895     -0.127917
4609      0.097347
7785      0.350941
9500     -0.032591
            ...
184623   -0.165147
187325    0.086537
188370   -0.006694
189704    0.400364
191856    0.022023
Name: Weight_Capacity_(kg), Length: 77, dtype: float64

In [37]:
X_test.isna().any()

Compartments                False
Weight_Capacity_(kg)         True
Brand_1_ohe                 False
Brand_2_ohe                 False
Brand_3_ohe                 False
Brand_4_ohe                 False
Brand_5_ohe                 False
Brand_6_ohe                 False
Material_1_ohe              False
Material_2_ohe              False
Material_3_ohe              False
Material_4_ohe              False
Material_5_ohe              False
Size_1_ohe                  False
Size_2_ohe                  False
Size_3_ohe                  False
Size_4_ohe                  False
Laptop_Compartment_1_ohe    False
Laptop_Compartment_2_ohe    False
Laptop_Compartment_3_ohe    False
Waterproof_1_ohe            False
Waterproof_2_ohe            False
Waterproof_3_ohe            False
Style_1_ohe                 False
Style_2_ohe                 False
Style_3_ohe                 False
Style_4_ohe                 False
Color_1_ohe                 False
Color_2_ohe                 False
Color_3_ohe                 False
Color_4_ohe                 False
Color_5_ohe                 False
Color_6_ohe                 False
Color_7_ohe                 False
dtype: bool

# After getting missing weights

In [38]:
n_splits = 10
random_state = 42
n_estimators = 9000 # 9999
early_stopping_rounds = 100
verbose = False
device = 'gpu'

# Initialize an array for storing test predictions
test_predss = np.zeros(X_test.shape[0])

test_predss_sub = []
ensemble_score = []
weights = []
regressor=Regressor(early_stopping_rounds=early_stopping_rounds)
trained_models = dict(zip(regressor.models.keys(), [[] for _ in range(regressor.len_models)]))

stratify_column=X_train['Compartments']

kf = StratifiedKFold(n_splits=n_splits, random_state=random_state, shuffle=True)
for i, (train_index, val_index) in enumerate(kf.split(X_train, stratify_column)):
    X_train_, X_val = X_train.iloc[train_index], X_train.iloc[val_index]
    y_train_, y_val = y_train.iloc[train_index], y_train.iloc[val_index]
        
    # Get a set of Regressor models
    rs = Regressor(early_stopping_rounds,n_estimators, device, random_state)
    models = rs.models
    
    # Initialize lists to store oof and test predictions for each base model
    oof_preds = []
    test_preds = []
    
    # Loop over each base model and fit it to the training data, evaluate on validation data, and store predictions
    for name, model in models.items():
        if name == 'cat_label':
            train_pool = Pool(X_train_, y_train_)#, cat_features=categorical_columns)
            test_pool = Pool(X_val, y_val)# ,cat_features=categorical_columns)
            model.fit(train_pool, eval_set=[test_pool], early_stopping_rounds=early_stopping_rounds, verbose=verbose)
        elif name == 'lgb_label':
            model.fit(X_train_, y_train_, eval_set=[(X_val, y_val)])
        elif name in ['xgb', 'lgb', 'cat']:
            model.fit(X_train_, y_train_, eval_set=[(X_val, y_val)])
        else:
            model.fit(X_train_fillna.iloc[train_index], y_train_)
        
        
        # if name in ['xgb', 'lgb', 'cat', 'cat_label', 'lgb_label']:
        #     test_pred = model.predict_proba(X_test)[:, 1]
        #     y_val_pred = model.predict_proba(X_val)[:, 1]
        # else:
        #     test_pred = model.predict_proba(X_test_fillna)[:, 1]
        #     y_val_pred = model.predict_proba(X_train_fillna.iloc[val_index])[:, 1]
        
        test_pred=model.predict(X_test)
        y_val_pred=model.predict(X_val)
        score = root_mean_squared_error(y_val, y_val_pred)
        print(f'{name} model [FOLD-{i}] RMSE: {score:.5f}')
        
        oof_preds.append(y_val_pred)
        test_preds.append(test_pred)
        trained_models[f'{name}'].append(deepcopy(model))
    
    # Use Optuna to find the best ensemble weights
    optweights = OptunaWeights(random_state=random_state)
    y_val_pred = optweights.fit_predict(y_val.values, oof_preds)

    #****** Not use Threshold because we do regression *****
    # Use Optuna to find the best threshold
    # opt = ThresholdOptimizer(y_val, y_val_pred, random_state)
    # opt.run_optimization(n_trials=2000)
    # best_threshold = opt.get_best_threshold()
    
    #score = accuracy_score(y_val, np.where(y_val_pred > best_threshold, 1, 0)) 
    score = root_mean_squared_error(y_val, y_val_pred)
    print(f'Ensemble [FOLD-{i}] RMSE score {score:.5f}')
    ensemble_score.append(score)
    weights.append(optweights.weights)
    
    test_predss_sub.append(optweights.predict(test_preds))
    print(f'result added {len(test_predss_sub)} items')
    #test_predss_onehot.append(np.where(optweights.predict(test_preds) > best_threshold, 1, 0))
    #gc.collect()

[0]	validation_0-rmse:38.91353
[1]	validation_0-rmse:38.91011
[2]	validation_0-rmse:38.90693
[3]	validation_0-rmse:38.90416
[4]	validation_0-rmse:38.90161
[5]	validation_0-rmse:38.89939
[6]	validation_0-rmse:38.89730
[7]	validation_0-rmse:38.89533
[8]	validation_0-rmse:38.89350
[9]	validation_0-rmse:38.89174
[10]	validation_0-rmse:38.88996
[11]	validation_0-rmse:38.88857
[12]	validation_0-rmse:38.88722
[13]	validation_0-rmse:38.88593
[14]	validation_0-rmse:38.88453
[15]	validation_0-rmse:38.88334
[16]	validation_0-rmse:38.88216
[17]	validation_0-rmse:38.88090
[18]	validation_0-rmse:38.87995
[19]	validation_0-rmse:38.87901
[20]	validation_0-rmse:38.87825
[21]	validation_0-rmse:38.87729
[22]	validation_0-rmse:38.87644
[23]	validation_0-rmse:38.87577
[24]	validation_0-rmse:38.87508
[25]	validation_0-rmse:38.87433
[26]	validation_0-rmse:38.87375
[27]	validation_0-rmse:38.87334
[28]	validation_0-rmse:38.87268
[29]	validation_0-rmse:38.87195
[30]	validation_0-rmse:38.87142
[31]	validation_0-rmse:38.87073
[32]	validation_0-rmse:38.86995
[33]	validation_0-rmse:38.86933
[34]	validation_0-rmse:38.86853
[35]	validation_0-rmse:38.86797
[36]	validation_0-rmse:38.86757
[37]	validation_0-rmse:38.86720
[38]	validation_0-rmse:38.86686
[39]	validation_0-rmse:38.86647
[40]	validation_0-rmse:38.86617
[41]	validation_0-rmse:38.86598
[42]	validation_0-rmse:38.86578
[43]	validation_0-rmse:38.86555
[44]	validation_0-rmse:38.86528
[45]	validation_0-rmse:38.86510
[46]	validation_0-rmse:38.86482
[47]	validation_0-rmse:38.86462
[48]	validation_0-rmse:38.86426
[49]	validation_0-rmse:38.86414
[50]	validation_0-rmse:38.86381
[51]	validation_0-rmse:38.86354
[52]	validation_0-rmse:38.86345
[53]	validation_0-rmse:38.86318
[54]	validation_0-rmse:38.86282
[55]	validation_0-rmse:38.86254
[56]	validation_0-rmse:38.86242
[57]	validation_0-rmse:38.86218
[58]	validation_0-rmse:38.86188
[59]	validation_0-rmse:38.86172
[60]	validation_0-rmse:38.86151
[61]	validation_0-rmse:38.86136
[62]	validation_0-rmse:38.86117
[63]	validation_0-rmse:38.86110
[64]	validation_0-rmse:38.86093
[65]	validation_0-rmse:38.86086
[66]	validation_0-rmse:38.86079
[67]	validation_0-rmse:38.86068
[68]	validation_0-rmse:38.86061
[69]	validation_0-rmse:38.86044
[70]	validation_0-rmse:38.86028
[71]	validation_0-rmse:38.86014
[72]	validation_0-rmse:38.85999
[73]	validation_0-rmse:38.85975
[74]	validation_0-rmse:38.85971
[75]	validation_0-rmse:38.85952
[76]	validation_0-rmse:38.85946
[77]	validation_0-rmse:38.85941
[78]	validation_0-rmse:38.85930
[79]	validation_0-rmse:38.85911
[80]	validation_0-rmse:38.85914
[81]	validation_0-rmse:38.85905
[82]	validation_0-rmse:38.85901
[83]	validation_0-rmse:38.85893
[84]	validation_0-rmse:38.85878
[85]	validation_0-rmse:38.85872
[86]	validation_0-rmse:38.85864
[87]	validation_0-rmse:38.85848
[88]	validation_0-rmse:38.85852
[89]	validation_0-rmse:38.85850
[90]	validation_0-rmse:38.85848
[91]	validation_0-rmse:38.85833
[92]	validation_0-rmse:38.85834
[93]	validation_0-rmse:38.85830
[94]	validation_0-rmse:38.85821
[95]	validation_0-rmse:38.85822
[96]	validation_0-rmse:38.85815
[97]	validation_0-rmse:38.85821
[98]	validation_0-rmse:38.85818
[99]	validation_0-rmse:38.85814
[100]	validation_0-rmse:38.85803
[101]	validation_0-rmse:38.85791
[102]	validation_0-rmse:38.85786
[103]	validation_0-rmse:38.85784
[104]	validation_0-rmse:38.85774
[105]	validation_0-rmse:38.85774
[106]	validation_0-rmse:38.85767
[107]	validation_0-rmse:38.85757
[108]	validation_0-rmse:38.85753
[109]	validation_0-rmse:38.85735
[110]	validation_0-rmse:38.85732
[111]	validation_0-rmse:38.85731
[112]	validation_0-rmse:38.85721
[113]	validation_0-rmse:38.85716
[114]	validation_0-rmse:38.85711
[115]	validation_0-rmse:38.85703
[116]	validation_0-rmse:38.85701
[117]	validation_0-rmse:38.85701
[118]	validation_0-rmse:38.85704
[119]	validation_0-rmse:38.85695
[120]	validation_0-rmse:38.85675
[121]	validation_0-rmse:38.85665
[122]	validation_0-rmse:38.85666
[123]	validation_0-rmse:38.85660
[124]	validation_0-rmse:38.85656
[125]	validation_0-rmse:38.85645
[126]	validation_0-rmse:38.85653
[127]	validation_0-rmse:38.85648
[128]	validation_0-rmse:38.85641
[129]	validation_0-rmse:38.85644
[130]	validation_0-rmse:38.85645
[131]	validation_0-rmse:38.85627
[132]	validation_0-rmse:38.85627
[133]	validation_0-rmse:38.85617
[134]	validation_0-rmse:38.85620
[135]	validation_0-rmse:38.85618
[136]	validation_0-rmse:38.85615
[137]	validation_0-rmse:38.85617
[138]	validation_0-rmse:38.85619
[139]	validation_0-rmse:38.85610
[140]	validation_0-rmse:38.85609
[141]	validation_0-rmse:38.85611
[142]	validation_0-rmse:38.85606
[143]	validation_0-rmse:38.85606
[144]	validation_0-rmse:38.85606
[145]	validation_0-rmse:38.85607
[146]	validation_0-rmse:38.85608
[147]	validation_0-rmse:38.85602
[148]	validation_0-rmse:38.85598
[149]	validation_0-rmse:38.85596
[150]	validation_0-rmse:38.85592
[151]	validation_0-rmse:38.85592
[152]	validation_0-rmse:38.85591
[153]	validation_0-rmse:38.85584
[154]	validation_0-rmse:38.85577
[155]	validation_0-rmse:38.85577
[156]	validation_0-rmse:38.85571
[157]	validation_0-rmse:38.85565
[158]	validation_0-rmse:38.85566
[159]	validation_0-rmse:38.85555
[160]	validation_0-rmse:38.85549
[161]	validation_0-rmse:38.85542
[162]	validation_0-rmse:38.85547
[163]	validation_0-rmse:38.85549
[164]	validation_0-rmse:38.85553
[165]	validation_0-rmse:38.85561
[166]	validation_0-rmse:38.85557
[167]	validation_0-rmse:38.85554
[168]	validation_0-rmse:38.85553
[169]	validation_0-rmse:38.85554
[170]	validation_0-rmse:38.85549
[171]	validation_0-rmse:38.85553
[172]	validation_0-rmse:38.85553
[173]	validation_0-rmse:38.85547
[174]	validation_0-rmse:38.85547
[175]	validation_0-rmse:38.85551
[176]	validation_0-rmse:38.85555
[177]	validation_0-rmse:38.85557
[178]	validation_0-rmse:38.85560
[179]	validation_0-rmse:38.85553
[180]	validation_0-rmse:38.85549
[181]	validation_0-rmse:38.85551
[182]	validation_0-rmse:38.85550
[183]	validation_0-rmse:38.85554
[184]	validation_0-rmse:38.85559
[185]	validation_0-rmse:38.85551
[186]	validation_0-rmse:38.85554
[187]	validation_0-rmse:38.85555
[188]	validation_0-rmse:38.85554
[189]	validation_0-rmse:38.85550
[190]	validation_0-rmse:38.85550
[191]	validation_0-rmse:38.85554
[192]	validation_0-rmse:38.85559
[193]	validation_0-rmse:38.85555
[194]	validation_0-rmse:38.85549
[195]	validation_0-rmse:38.85549
[196]	validation_0-rmse:38.85541
[197]	validation_0-rmse:38.85536
[198]	validation_0-rmse:38.85534
[199]	validation_0-rmse:38.85537
[200]	validation_0-rmse:38.85539
[201]	validation_0-rmse:38.85539
[202]	validation_0-rmse:38.85536
[203]	validation_0-rmse:38.85536
[204]	validation_0-rmse:38.85533
[205]	validation_0-rmse:38.85528
[206]	validation_0-rmse:38.85526
[207]	validation_0-rmse:38.85531
[208]	validation_0-rmse:38.85531
[209]	validation_0-rmse:38.85531
[210]	validation_0-rmse:38.85530
[211]	validation_0-rmse:38.85529
[212]	validation_0-rmse:38.85528
[213]	validation_0-rmse:38.85532
[214]	validation_0-rmse:38.85535
[215]	validation_0-rmse:38.85530
[216]	validation_0-rmse:38.85529
[217]	validation_0-rmse:38.85530
[218]	validation_0-rmse:38.85532
[219]	validation_0-rmse:38.85534
[220]	validation_0-rmse:38.85534
[221]	validation_0-rmse:38.85538
[222]	validation_0-rmse:38.85537
[223]	validation_0-rmse:38.85535
[224]	validation_0-rmse:38.85535
[225]	validation_0-rmse:38.85537
[226]	validation_0-rmse:38.85537
[227]	validation_0-rmse:38.85534
[228]	validation_0-rmse:38.85534
[229]	validation_0-rmse:38.85534
[230]	validation_0-rmse:38.85536
[231]	validation_0-rmse:38.85539
[232]	validation_0-rmse:38.85542
[233]	validation_0-rmse:38.85543
[234]	validation_0-rmse:38.85541
[235]	validation_0-rmse:38.85541
[236]	validation_0-rmse:38.85542
[237]	validation_0-rmse:38.85542
[238]	validation_0-rmse:38.85535
[239]	validation_0-rmse:38.85534
[240]	validation_0-rmse:38.85534
[241]	validation_0-rmse:38.85537
[242]	validation_0-rmse:38.85540
[243]	validation_0-rmse:38.85537
[244]	validation_0-rmse:38.85536
[245]	validation_0-rmse:38.85540
[246]	validation_0-rmse:38.85537
[247]	validation_0-rmse:38.85536
[248]	validation_0-rmse:38.85537
[249]	validation_0-rmse:38.85537
[250]	validation_0-rmse:38.85539
[251]	validation_0-rmse:38.85532
[252]	validation_0-rmse:38.85536
[253]	validation_0-rmse:38.85539
[254]	validation_0-rmse:38.85544
[255]	validation_0-rmse:38.85547
[256]	validation_0-rmse:38.85547
[257]	validation_0-rmse:38.85556
[258]	validation_0-rmse:38.85552
[259]	validation_0-rmse:38.85552
[260]	validation_0-rmse:38.85553
[261]	validation_0-rmse:38.85564
[262]	validation_0-rmse:38.85563
[263]	validation_0-rmse:38.85563
[264]	validation_0-rmse:38.85565
[265]	validation_0-rmse:38.85566
[266]	validation_0-rmse:38.85566
[267]	validation_0-rmse:38.85562
[268]	validation_0-rmse:38.85560
[269]	validation_0-rmse:38.85560
[270]	validation_0-rmse:38.85559
[271]	validation_0-rmse:38.85562
[272]	validation_0-rmse:38.85564
[273]	validation_0-rmse:38.85570
[274]	validation_0-rmse:38.85570
[275]	validation_0-rmse:38.85570
[276]	validation_0-rmse:38.85571
[277]	validation_0-rmse:38.85571
[278]	validation_0-rmse:38.85567
[279]	validation_0-rmse:38.85567
[280]	validation_0-rmse:38.85565
[281]	validation_0-rmse:38.85569
[282]	validation_0-rmse:38.85571
[283]	validation_0-rmse:38.85567
[284]	validation_0-rmse:38.85565
[285]	validation_0-rmse:38.85564
[286]	validation_0-rmse:38.85567
[287]	validation_0-rmse:38.85574
[288]	validation_0-rmse:38.85578
[289]	validation_0-rmse:38.85577
[290]	validation_0-rmse:38.85585
[291]	validation_0-rmse:38.85590
[292]	validation_0-rmse:38.85593
[293]	validation_0-rmse:38.85591
[294]	validation_0-rmse:38.85592
[295]	validation_0-rmse:38.85592
[296]	validation_0-rmse:38.85595
[297]	validation_0-rmse:38.85591
[298]	validation_0-rmse:38.85598
[299]	validation_0-rmse:38.85604
[300]	validation_0-rmse:38.85603
[301]	validation_0-rmse:38.85597
[302]	validation_0-rmse:38.85604
[303]	validation_0-rmse:38.85601
[304]	validation_0-rmse:38.85604
[305]	validation_0-rmse:38.85602
xgb model [FOLD-0] RMSE: 38.85526
[LightGBM] [Warning] early_stopping_round is set=100, early_stopping_rounds=100 will be ignored. Current value: early_stopping_round=100
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 330
[LightGBM] [Info] Number of data points in the train set: 3593259, number of used features: 34
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 9 dense feature groups (41.12 MB) transferred to GPU in 0.065972 secs. 0 sparse feature groups
[LightGBM] [Warning] early_stopping_round is set=100, early_stopping_rounds=100 will be ignored. Current value: early_stopping_round=100
[LightGBM] [Info] Start training from score 81.367976
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[519]	valid_0's rmse: 38.8492
lgb model [FOLD-0] RMSE: 38.84915
0:	learn: 38.9293423	test: 38.9102776	best: 38.9102776 (0)	total: 83.6ms	remaining: 12m 32s
1:	learn: 38.9229035	test: 38.9040192	best: 38.9040192 (1)	total: 120ms	remaining: 8m 57s
2:	learn: 38.9173313	test: 38.8985881	best: 38.8985881 (2)	total: 156ms	remaining: 7m 48s
3:	learn: 38.9126793	test: 38.8941290	best: 38.8941290 (3)	total: 193ms	remaining: 7m 13s
4:	learn: 38.9088746	test: 38.8904030	best: 38.8904030 (4)	total: 229ms	remaining: 6m 51s
5:	learn: 38.9052251	test: 38.8868333	best: 38.8868333 (5)	total: 263ms	remaining: 6m 33s
6:	learn: 38.9023976	test: 38.8844774	best: 38.8844774 (6)	total: 295ms	remaining: 6m 19s
7:	learn: 38.8997823	test: 38.8821255	best: 38.8821255 (7)	total: 327ms	remaining: 6m 7s
8:	learn: 38.8976174	test: 38.8804145	best: 38.8804145 (8)	total: 359ms	remaining: 5m 58s
9:	learn: 38.8950934	test: 38.8781221	best: 38.8781221 (9)	total: 390ms	remaining: 5m 50s
10:	learn: 38.8932781	test: 38.8766130	best: 38.8766130 (10)	total: 419ms	remaining: 5m 42s
11:	learn: 38.8913822	test: 38.8749142	best: 38.8749142 (11)	total: 447ms	remaining: 5m 34s
12:	learn: 38.8893029	test: 38.8732730	best: 38.8732730 (12)	total: 476ms	remaining: 5m 29s
13:	learn: 38.8877952	test: 38.8720606	best: 38.8720606 (13)	total: 502ms	remaining: 5m 22s
14:	learn: 38.8864999	test: 38.8712111	best: 38.8712111 (14)	total: 529ms	remaining: 5m 16s
15:	learn: 38.8848638	test: 38.8698543	best: 38.8698543 (15)	total: 556ms	remaining: 5m 12s
16:	learn: 38.8836289	test: 38.8690666	best: 38.8690666 (16)	total: 583ms	remaining: 5m 7s
17:	learn: 38.8819029	test: 38.8676355	best: 38.8676355 (17)	total: 608ms	remaining: 5m 3s
18:	learn: 38.8808676	test: 38.8668911	best: 38.8668911 (18)	total: 634ms	remaining: 4m 59s
19:	learn: 38.8793852	test: 38.8657672	best: 38.8657672 (19)	total: 658ms	remaining: 4m 55s
20:	learn: 38.8784249	test: 38.8652145	best: 38.8652145 (20)	total: 684ms	remaining: 4m 52s
21:	learn: 38.8773438	test: 38.8646701	best: 38.8646701 (21)	total: 710ms	remaining: 4m 49s
22:	learn: 38.8764385	test: 38.8641421	best: 38.8641421 (22)	total: 736ms	remaining: 4m 47s
23:	learn: 38.8752839	test: 38.8633502	best: 38.8633502 (23)	total: 761ms	remaining: 4m 44s
24:	learn: 38.8744409	test: 38.8628264	best: 38.8628264 (24)	total: 787ms	remaining: 4m 42s
25:	learn: 38.8735319	test: 38.8621581	best: 38.8621581 (25)	total: 815ms	remaining: 4m 41s
26:	learn: 38.8728574	test: 38.8618467	best: 38.8618467 (26)	total: 841ms	remaining: 4m 39s
27:	learn: 38.8721683	test: 38.8613538	best: 38.8613538 (27)	total: 867ms	remaining: 4m 37s
28:	learn: 38.8711859	test: 38.8608258	best: 38.8608258 (28)	total: 892ms	remaining: 4m 35s
29:	learn: 38.8700312	test: 38.8600585	best: 38.8600585 (29)	total: 916ms	remaining: 4m 33s
30:	learn: 38.8693274	test: 38.8597636	best: 38.8597636 (30)	total: 942ms	remaining: 4m 32s
31:	learn: 38.8686987	test: 38.8595800	best: 38.8595800 (31)	total: 968ms	remaining: 4m 31s
32:	learn: 38.8680186	test: 38.8592562	best: 38.8592562 (32)	total: 994ms	remaining: 4m 30s
33:	learn: 38.8674247	test: 38.8589406	best: 38.8589406 (33)	total: 1.02s	remaining: 4m 29s
34:	learn: 38.8667832	test: 38.8585302	best: 38.8585302 (34)	total: 1.05s	remaining: 4m 28s
35:	learn: 38.8660793	test: 38.8582352	best: 38.8582352 (35)	total: 1.07s	remaining: 4m 26s
36:	learn: 38.8655330	test: 38.8579093	best: 38.8579093 (36)	total: 1.1s	remaining: 4m 25s
37:	learn: 38.8648474	test: 38.8576742	best: 38.8576742 (37)	total: 1.12s	remaining: 4m 24s
38:	learn: 38.8639950	test: 38.8571544	best: 38.8571544 (38)	total: 1.15s	remaining: 4m 23s
39:	learn: 38.8634249	test: 38.8570636	best: 38.8570636 (39)	total: 1.17s	remaining: 4m 22s
40:	learn: 38.8626806	test: 38.8565232	best: 38.8565232 (40)	total: 1.2s	remaining: 4m 21s
41:	learn: 38.8619327	test: 38.8561478	best: 38.8561478 (41)	total: 1.22s	remaining: 4m 21s
42:	learn: 38.8614560	test: 38.8559353	best: 38.8559353 (42)	total: 1.25s	remaining: 4m 20s
43:	learn: 38.8608730	test: 38.8556940	best: 38.8556940 (43)	total: 1.27s	remaining: 4m 19s
44:	learn: 38.8603157	test: 38.8555248	best: 38.8555248 (44)	total: 1.3s	remaining: 4m 18s
45:	learn: 38.8598023	test: 38.8555104	best: 38.8555104 (45)	total: 1.32s	remaining: 4m 17s
46:	learn: 38.8593238	test: 38.8553969	best: 38.8553969 (46)	total: 1.35s	remaining: 4m 17s
47:	learn: 38.8586473	test: 38.8550751	best: 38.8550751 (47)	total: 1.37s	remaining: 4m 16s
48:	learn: 38.8581229	test: 38.8550236	best: 38.8550236 (48)	total: 1.4s	remaining: 4m 15s
49:	learn: 38.8576939	test: 38.8548647	best: 38.8548647 (49)	total: 1.43s	remaining: 4m 15s
50:	learn: 38.8572264	test: 38.8546997	best: 38.8546997 (50)	total: 1.45s	remaining: 4m 14s
51:	learn: 38.8566928	test: 38.8544934	best: 38.8544934 (51)	total: 1.48s	remaining: 4m 14s
52:	learn: 38.8562363	test: 38.8544068	best: 38.8544068 (52)	total: 1.5s	remaining: 4m 13s
53:	learn: 38.8556734	test: 38.8541201	best: 38.8541201 (53)	total: 1.53s	remaining: 4m 13s
54:	learn: 38.8551545	test: 38.8539633	best: 38.8539633 (54)	total: 1.55s	remaining: 4m 12s
55:	learn: 38.8547382	test: 38.8538086	best: 38.8538086 (55)	total: 1.57s	remaining: 4m 11s
56:	learn: 38.8543202	test: 38.8537776	best: 38.8537776 (56)	total: 1.6s	remaining: 4m 11s
57:	learn: 38.8536986	test: 38.8535053	best: 38.8535053 (57)	total: 1.63s	remaining: 4m 10s
58:	learn: 38.8532475	test: 38.8534166	best: 38.8534166 (58)	total: 1.65s	remaining: 4m 10s
59:	learn: 38.8526845	test: 38.8533712	best: 38.8533712 (59)	total: 1.68s	remaining: 4m 10s
60:	learn: 38.8521161	test: 38.8531897	best: 38.8531897 (60)	total: 1.71s	remaining: 4m 10s
61:	learn: 38.8517677	test: 38.8530350	best: 38.8530350 (61)	total: 1.73s	remaining: 4m 9s
62:	learn: 38.8513459	test: 38.8528514	best: 38.8528514 (62)	total: 1.76s	remaining: 4m 9s
63:	learn: 38.8509571	test: 38.8529009	best: 38.8528514 (62)	total: 1.79s	remaining: 4m 9s
64:	learn: 38.8505537	test: 38.8528844	best: 38.8528514 (62)	total: 1.81s	remaining: 4m 9s
65:	learn: 38.8500677	test: 38.8526472	best: 38.8526472 (65)	total: 1.84s	remaining: 4m 8s
66:	learn: 38.8495891	test: 38.8524347	best: 38.8524347 (66)	total: 1.86s	remaining: 4m 8s
67:	learn: 38.8491471	test: 38.8523687	best: 38.8523687 (67)	total: 1.89s	remaining: 4m 7s
68:	learn: 38.8487675	test: 38.8522779	best: 38.8522779 (68)	total: 1.91s	remaining: 4m 7s
69:	learn: 38.8483531	test: 38.8520799	best: 38.8520799 (69)	total: 1.94s	remaining: 4m 6s
70:	learn: 38.8479533	test: 38.8518406	best: 38.8518406 (70)	total: 1.96s	remaining: 4m 6s
71:	learn: 38.8476085	test: 38.8518199	best: 38.8518199 (71)	total: 1.98s	remaining: 4m 6s
72:	learn: 38.8472399	test: 38.8518942	best: 38.8518199 (71)	total: 2.01s	remaining: 4m 5s
73:	learn: 38.8469189	test: 38.8519066	best: 38.8518199 (71)	total: 2.03s	remaining: 4m 5s
74:	learn: 38.8465778	test: 38.8518983	best: 38.8518199 (71)	total: 2.06s	remaining: 4m 5s
75:	learn: 38.8462293	test: 38.8518983	best: 38.8518199 (71)	total: 2.08s	remaining: 4m 4s
76:	learn: 38.8458680	test: 38.8518571	best: 38.8518199 (71)	total: 2.11s	remaining: 4m 4s
77:	learn: 38.8454425	test: 38.8517910	best: 38.8517910 (77)	total: 2.13s	remaining: 4m 4s
78:	learn: 38.8449748	test: 38.8517704	best: 38.8517704 (78)	total: 2.16s	remaining: 4m 3s
79:	learn: 38.8444943	test: 38.8517580	best: 38.8517580 (79)	total: 2.18s	remaining: 4m 3s
80:	learn: 38.8441807	test: 38.8517993	best: 38.8517580 (79)	total: 2.21s	remaining: 4m 2s
81:	learn: 38.8438102	test: 38.8517745	best: 38.8517580 (79)	total: 2.23s	remaining: 4m 2s
82:	learn: 38.8433682	test: 38.8517498	best: 38.8517498 (82)	total: 2.25s	remaining: 4m 2s
83:	learn: 38.8428766	test: 38.8517209	best: 38.8517209 (83)	total: 2.28s	remaining: 4m 1s
84:	learn: 38.8425520	test: 38.8516590	best: 38.8516590 (84)	total: 2.3s	remaining: 4m 1s
85:	learn: 38.8422273	test: 38.8516487	best: 38.8516487 (85)	total: 2.33s	remaining: 4m 1s
86:	learn: 38.8418458	test: 38.8515476	best: 38.8515476 (86)	total: 2.35s	remaining: 4m 1s
87:	learn: 38.8414863	test: 38.8515229	best: 38.8515229 (87)	total: 2.38s	remaining: 4m 1s
88:	learn: 38.8410846	test: 38.8516012	best: 38.8515229 (87)	total: 2.4s	remaining: 4m
89:	learn: 38.8405838	test: 38.8514692	best: 38.8514692 (89)	total: 2.43s	remaining: 4m
90:	learn: 38.8402243	test: 38.8514837	best: 38.8514692 (89)	total: 2.45s	remaining: 4m
91:	learn: 38.8398795	test: 38.8514651	best: 38.8514651 (91)	total: 2.48s	remaining: 4m
92:	learn: 38.8394044	test: 38.8512547	best: 38.8512547 (92)	total: 2.5s	remaining: 3m 59s
93:	learn: 38.8390173	test: 38.8513331	best: 38.8512547 (92)	total: 2.53s	remaining: 3m 59s
94:	learn: 38.8386211	test: 38.8513269	best: 38.8512547 (92)	total: 2.55s	remaining: 3m 59s
95:	learn: 38.8381552	test: 38.8512732	best: 38.8512547 (92)	total: 2.58s	remaining: 3m 59s
96:	learn: 38.8377699	test: 38.8511886	best: 38.8511886 (96)	total: 2.6s	remaining: 3m 58s
97:	learn: 38.8373444	test: 38.8510360	best: 38.8510360 (97)	total: 2.63s	remaining: 3m 58s

In [39]:
# import numpy as np
# import pandas as pd

# E=[]
# a=np.array([1.,1.,1.])
# b=np.array([2.,2.,2.])

# c=np.array([a,b])
# d=c.T
# print(np.average(d,axis=1,weights=[[1,2],[1,2],[1,2]]))

# E.append(a)
# E.append(b)
# F=np.median(E,axis=0)
# print(F)

# Evaluation

In [40]:
# Calculate the mean LogLoss score of the ensemble
mean_score = np.mean(ensemble_score)
std_score = np.std(ensemble_score)
print(f'Ensemble Accuracy score {mean_score:.5f} ± {std_score:.5f}')

# Print the mean and standard deviation of the ensemble weights for each model
print('--- Model Weights ---')
mean_weights = np.mean(weights, axis=0)
std_weights = np.std(weights, axis=0)
for name, mean_weight, std_weight in zip(models.keys(), mean_weights, std_weights):
    print(f'{name} {mean_weight:.5f} ± {std_weight:.5f}')

Ensemble Accuracy score 38.86677 ± 0.02650
--- Model Weights ---
xgb 0.18247 ± 0.10041
lgb 0.67286 ± 0.13095
cat 0.24587 ± 0.18096

# Submission#

In [41]:
df_sub['Price'] = np.median(test_predss_sub, axis=0)
df_sub.to_csv('submission.csv',index=False)
df_sub.head(5)

       id      Price
0  300000  80.911542
1  300001  82.572984
2  300002  82.902290
3  300003  80.892026
4  300004  79.255460